server:
  error:
    include-message: always
    include-blinding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
    password: 1Chiemelienwobodo@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
